### ISSUE TITLE
please use consistent indentation

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/libfastjson#57]
currently, the libfastjson sources use a wild mixture of 2 space, 4 space or tab indentation and even a mixture (tab + spaces).
This makes the code unnecessarily hard to read and inconsistent.

Please consider indentation scheme.

**Comment by rgerhards** [comment]
Yes... Well... I don't like it either, but I really don't think it's a
critical point. It takes quite a while to fix this and there is so much to
do. I've used some tools in the past, but nothing worked really well.

Sent from phone, thus brief.
Am 08.04.2016 22:21 schrieb "Michael Biebl" <notifications@github.com>:

**Comment by davidelang** [comment]
Why would a pass through indent take much time to do?

We would want to plan when to do it (since it would change so much stuff, 
affecting the git history)

David Lang

**Comment by rgerhards** [comment]
I think I used indent as well in the past, and a lot of indention was wrong
and pretty misleading. I can give it another try, but I need to verify the
result. Given the fact that I need to release in roughly a week and Michael
prefers all cleanup by done by then, I would prefer not to deal with this
right now.

Sent from phone, thus brief.
Am 08.04.2016 22:31 schrieb "davidelang" <notifications@github.com>:

**Comment by mbiebl** [comment]
2016-04-08 22:50 GMT+02:00 Rainer Gerhards <notifications@github.com>:

> I think I used indent as well in the past, and a lot of indention was wrong
> and pretty misleading. I can give it another try, but I need to verify the
> result. Given the fact that I need to release in roughly a week and Michael
> prefers all cleanup by done by then, I would prefer not to deal with this
> right now.


As I mentioned before, I would prefer that we take the time to polish
libfastjson before we make another release instead of rushing something.
timebased releases are fine, but they shouldn't be an artificial burden.
Just skip the next release date and we'll release it the next cycle.


-- 
Why is it that all of the instruments seeking intelligent life in the
universe are pointed away from Earth?

**Comment by davidelang** [comment]
On Fri, 8 Apr 2016, Michael Biebl wrote:

> 2016-04-08 22:50 GMT+02:00 Rainer Gerhards <notifications@github.com>:
>
>> I think I used indent as well in the past, and a lot of indention was wrong
>> and pretty misleading. I can give it another try, but I need to verify the
>> result. Given the fact that I need to release in roughly a week and Michael
>> prefers all cleanup by done by then, I would prefer not to deal with this
>> right now.
>
>
> As I mentioned before, I would prefer that we take the time to polish
> libfastjson before we make another release instead of rushing something.
> timebased releases are fine, but they shouldn't be an artificial burden.
> Just skip the next release date and we'll release it the next cycle.

If we could release the updates for rsyslog, liblognorm, etc without changing 
libfastjson I would be ok with delaying a new version of libfastjson until the 
next cycle.

but I really don't want the fact that we are doing cleanup/restructuring of one 
library that we use to block all the other improvements from going out.

with 20-20 hindsight, it may be that we should have been doing all this work off 
on a branch so that the work could span multiple releases without being visible 
until it's done. But when we started, we weren't expecting to do this much, let 
alone this quickly.

If I undertand it, the concern is that the libfastjson API is very unstable as 
we are stripping it down and cleaning it up, and you don't want to ship it at 
all until things get better.

while I would also like things to be really good, I'll point out that even the 
existing version has very significant advantages over json-c (not segfaulting or 
corrupting messages due to thread safety issues for example), and wonder if we 
are falling into the trap of making perfect be the enemy of better.

Things like indentation should wait until the release after the API and other 
major functional changes settle down, so that whitespace changes don't confuse 
investigating any issues that we run into.

Michael, you've already effectively skipped one rsyslog release, does it make a 
difference if skipping a second one is done on your side instead of on the 
rsyslog side? Is there any way to put the packages in Unstable and not have them 
graduate into the other versions so that people who need them can get them, but 
you don't risk pushing them out to everyone until things have settled a bit 
more?

David Lang

**Comment by rgerhards** [comment]
Well, I originally didn't want to touch libfastjson much in this cycle. But
then it looked like the right thing to do now. Bottom line is that I don't
need libfastjson for the next release. It just becomes somewhat tricky in
regard to CI and especially Travis. So i can concentrate again on rsyslog
and move the libfastjson work to after the release. I had hoped to get a
better state of libfastjson into the release, but it doesn't overall hurt
so much if we don't make it.

@mbiebl in any case, I don't think we should release 1.0.0 as final, but
rather a "not fully finished" 0.99 version from which we can get some
experience before we guarantee a stable API.
Am 08.04.2016 23:11 schrieb "davidelang" <notifications@github.com>:

**Comment by mbiebl** [comment]
@davidelang regarding debian, I'm not concerned. I'll just skip as many releases until I'm happy. I'm simply concerned that we end up releasing an intermediate state which we'll need to support for a long time.
If we just release 0.99.3 which is 0.99.2 + a few bug fixes, then okay.
But the current state in master is not ready yet imho.

**Comment by davidelang** [comment]
On Fri, 8 Apr 2016, Michael Biebl wrote:

> @davidelang regarding debian, I'm not concerned. I'll just skip as many 
> releases until I'm happy. I'm simply concerned that we end up releasing an 
> intermediate state which we'll need to support for a long time.

We want you happy, besides being the maintainer, you are identifying things that 
do need to be fixed at some point :-)

I especially agree with wanting to avoid supporting in intermediate state for a 
long time. What are the cutoff times for the next point where such 
long-term-support is going to kick in?

> If we just release 0.99.3 which is 0.99.2 + a few bug fixes, then okay.

Rainer, there's been a ton of work on libfastjson, has much of it been fixing 
bugs that were seen in 0.99.2? or is it almost all the cleanup/speedup type 
stuff (including bugs that existed in older versions, but had not been 
seen/reported?)

> But the current state in master is not ready yet imho.

not ready, even os 0.99.3? (I agree it's not nearly 1.0)

As I'm seeing things, a very large percentage of the stuff that's problematic in 
libfastjson is inherited from json-c.

David Lang

**Comment by rgerhards** [comment]
2016-04-09 0:16 GMT+02:00 davidelang <notifications@github.com>:
>
> On Fri, 8 Apr 2016, Michael Biebl wrote:
>
> > @davidelang regarding debian, I'm not concerned. I'll just skip as many
> > releases until I'm happy. I'm simply concerned that we end up releasing an
> > intermediate state which we'll need to support for a long time.
>

I think I can address that concern: I, too, do not want to support
something for a long term that's not ready. That's why I used 0.99 in
the first place, and I have amended the README.md as one of the first
things in this iteration. It now contains:

"IMPORTANT The current API is not stable and will change until version
1.0.0 is reached. We plan to reach it by summer 2016 at latest. With
1.0.0, the API will be stable. Until then, everything may change. Of
course, we will not deliberatly break things but we need freedom to
restructure."

see: https://github.com/rsyslog/libfastjson/blob/master/README.md

In other words: anyone who uses 0.99 must be prepared for total
change. I still think it is useful to have interim releases,
especially as I want to get some experience with the changes and it
greatly reduces the risk of totally breaking something compared to
doing one really big release with lots of new code all over all
projects.

It's perfectly fine with me if distros do not pick up the interim
versions (and it is of course not of my cocern either).

> We want you happy, besides being the maintainer, you are identifying things that
> do need to be fixed at some point :-)

Full ACK! I deeply appreciate all the good advise Michael has given
over all those years and hope he will continue to do so. It helps
greatly in making things better. I've also seen a couple of things
that I can change in the other projects based on what we have
discussed the past couple of days.

>
> I especially agree with wanting to avoid supporting in intermediate state for a
> long time. What are the cutoff times for the next point where such
> long-term-support is going to kick in?

see above - 1.0.0 whenever it is ready

>
> > If we just release 0.99.3 which is 0.99.2 + a few bug fixes, then okay.
>
> Rainer, there's been a ton of work on libfastjson, has much of it been fixing
> bugs that were seen in 0.99.2? or is it almost all the cleanup/speedup type
> stuff (including bugs that existed in older versions, but had not been
> seen/reported?)

everything I have done this week is cleanup work and *fixes to json-c*
code base. The 0.99.2 and json-c master code bases are not much
different yet (except for the well-known ciritical spots, maybe 200
LoC).

I, too, think that it makes a lot of sense to do much cleanup before
even going to further speedup. There is one notable exception: I don't
think it makes sense to cleanup code that will probably be removed
very soon (namely everything related to hash tables). Here, I think we
need to first find out if there is need for it to stay or not. Of
course, some minor cleanup may still be necessary, e.g. to get fixes
to the build system into place. This is also one of the areas where I
am hesitant to do it "all at once", as I need to get some experience
with new features, and I mean feedback from paractice rather than
(only) theoretical testing. Thus, we need to release some of these
versions.

>
> > But the current state in master is not ready yet imho.
>
> not ready, even os 0.99.3? (I agree it's not nearly 1.0)
>
> As I'm seeing things, a very large percentage of the stuff that's problematic in
> libfastjson is inherited from json-c.

Yes, most things we changed this week apply to json-c as well. But
that's probaly a different story, as this is in distro archives for
years, and so was entered under different policies. For a new project,
even a fork, we should try to start as clean as possible. As the code
is not much (and shrinking), I think we can try to cleanup everything
here.

After some more thinking and this last exchange, I think I'll probably
do a 0.99.3 release as originally planned, and maybe some more 0.99
releases. It's up to the distros to decide if they pick it at all,
pick the interims or pick 1.0. I can put code into rsyslog to build
with different versions, just like we did with json-c.

Back to the original topic: I think we should not only talk about
indention, but rather coding style in general. I would tend to try to
change things to gnome style, but that's probably the topic for a
broader (mailing list) discussion.

**Comment by rgerhards** [comment]
I have done a round of manual changes, which covers most of the probably-to-stay indentions. That review however stresses the point that there are more readability issues. The code is at places very dense (e.g multiple statements on one line). So the question of code style is definitely one to consider.

Note that I touched the files at an instant where no larger PRs are outstanding and everything done so far is consistently completed. So the effect on git history should not be too bad.
